### ISSUE TITLE
[ Bug ] Tool crashes after Module updates

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#171]
**Describe the bug**
Can't restart tool after module updates

**To Reproduce**
1. Open Tool in Browser
2. Start Module updates
3. Restart tool

**Expected behavior**
An easy restart without problems is possible

**Screenshots**
`2022-12-03T20:49:17.148Z [error] plugin-config: Uncaught error in plugin-config:                                                                                                  ENOENT: no such file or directory, open '/root/league-prod-toolkit/modules/plu                                                                                                gin-config/config.json'
Error: ENOENT: no such file or directory, open '/root/league-prod-toolkit/module                                                                                                s/plugin-config/config.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at module.exports (/root/league-prod-toolkit/modules/plugin-config/dist/plug                                                                                                in.js:8:45)
    at Plugin.initialize (/root/league-prod-toolkit/dist/core/modules/Module.js:                                                                                                128:30)
    at /root/league-prod-toolkit/dist/core/modules/ModuleService.js:120:20
    at Array.forEach (<anonymous>)
    at ModuleService.initialize (/root/league-prod-toolkit/dist/core/modules/Mod                                                                                                uleService.js:119:28)
    at async main (/root/league-prod-toolkit/dist/core/app.js:42:5) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/league-prod-toolkit/modules/plugin-config/config.json'
}
`

**System:**

- OS: Ubuntu 20.04.5 LTS
- Prod Tool Version: 1.3.4
- Observer Tool Version: 3.1.5

**Comment by MaximilianRu** [comment]
There might be a Problem with me killing the Process to fast, because no visual indicator is available whether the module has finished updating or not.

But maybe there is an other bug which is the reason of the problem

**Comment by Himyu** [comment]
There is a  message in the console/log when it's finished updating

**Comment by MaximilianRu** [comment]
Since the toolkit is hosted externaly I normaly don't use the console, just the browser interface.

**Comment by Himyu** [comment]
Since there is more of the issue of it not being displayed in frontend I will close this issue and we will track it further in #172
