### ISSUE TITLE
[ Question ] Developing on this project.

### ISSUE THREAD

**Issue by JoanJuan10** [RCVolus/league-prod-toolkit#236]
**Is your question related to a problem? Please describe.**
Following the Developer Documentation. On a fresh clone, I am having problems gathering the submodules and all folders seem empty.

**Describe alternatives you've considered**
I have tried doing the same after on a sucessful install and neither seems to work.

**Additional context**
Here's the cmd output:

```
$ git clone https://github.com/RCVolus/league-prod-toolkit.git
Cloning into 'league-prod-toolkit'...
remote: Enumerating objects: 5116, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 5116 (delta 157), reused 190 (delta 114), pack-reused 4867
Receiving objects: 100% (5116/5116), 28.50 MiB | 11.78 MiB/s, done.
Resolving deltas: 100% (3107/3107), done.

Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios
$ cd league-prod-toolkit

Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ git submodule update --init --recursive
Submodule 'docs/wiki' (https://github.com/RCVolus/league-prod-toolkit.wiki.git) registered for path 'docs/wiki'
Submodule 'modules/module-caster' (https://github.com/rcv-prod-toolkit/module-caster.git) registered for path 'modules/module-caster'
Submodule 'modules/module-league-caster-cockpit' (https://github.com/rcv-prod-toolkit/module-league-caster-cockpit.git) registered for path 'modules/module-league-caster-cockpit'
Submodule 'modules/module-league-champselect-ace' (https://github.com/rcv-prod-toolkit/module-league-champselect-ace.git) registered for path 'modules/module-league-champselect-ace'
Submodule 'modules/module-league-champselect-tent' (https://github.com/rcv-prod-toolkit/module-league-champselect-tent.git) registered for path 'modules/module-league-champselect-tent'
Submodule 'modules/module-league-champselect-ui' (https://github.com/rcv-prod-toolkit/module-league-champselect-ui.git) registered for path 'modules/module-league-champselect-ui'
Submodule 'modules/module-league-end-of-game' (https://github.com/rcv-prod-toolkit/module-league-end-of-game.git) registered for path 'modules/module-league-end-of-game'
Submodule 'modules/module-league-in-game' (https://github.com/rcv-prod-toolkit/module-league-in-game.git) registered for path 'modules/module-league-in-game'
Submodule 'modules/module-league-prm' (https://github.com/rcv-prod-toolkit/module-league-prm.git) registered for path 'modules/module-league-prm'
Submodule 'modules/module-league-runes' (https://github.com/rcv-prod-toolkit/module-league-runes.git) registered for path 'modules/module-league-runes'
Submodule 'modules/module-league-state' (https://github.com/rcv-prod-toolkit/module-league-state.git) registered for path 'modules/module-league-state'
Submodule 'modules/module-league-static' (https://github.com/rcv-prod-toolkit/module-league-static.git) registered for path 'modules/module-league-static'
Submodule 'modules/module-teams' (https://github.com/rcv-prod-toolkit/module-teams.git) registered for path 'modules/module-teams'
Submodule 'modules/module-tournament-tree' (https://github.com/rcv-prod-toolkit/module-tournament-tree.git) registered for path 'modules/module-tournament-tree'
Submodule 'modules/module-twitch' (https://github.com/rcv-prod-toolkit/module-twitch.git) registered for path 'modules/module-twitch'
Submodule 'modules/module-valorant-pregame' (https://github.com/rcv-prod-toolkit/module-valorant-pregame.git) registered for path 'modules/module-valorant-pregame'
Submodule 'modules/module-valorant-state' (https://github.com/rcv-prod-toolkit/module-valorant-state.git) registered for path 'modules/module-valorant-state'
Submodule 'modules/module-valorant-static' (https://github.com/rcv-prod-toolkit/module-valorant-static.git) registered for path 'modules/module-valorant-static'
Submodule 'modules/module-vmix' (https://github.com/rcv-prod-toolkit/module-vmix.git) registered for path 'modules/module-vmix'
Submodule 'modules/plugin-config' (https://github.com/rcv-prod-toolkit/plugin-config.git) registered for path 'modules/plugin-config'
Submodule 'modules/plugin-database' (https://github.com/rcv-prod-toolkit/plugin-database.git) registered for path 'modules/plugin-database'
Submodule 'modules/plugin-prod-clock' (https://github.com/rcv-prod-toolkit/plugin-prod-clock.git) registered for path 'modules/plugin-prod-clock'
Submodule 'modules/plugin-theming' (https://github.com/rcv-prod-toolkit/plugin-theming.git) registered for path 'modules/plugin-theming'
Submodule 'modules/plugin-webapi' (https://github.com/rcv-prod-toolkit/plugin-webapi.git) registered for path 'modules/plugin-webapi'
Submodule 'types' (https://github.com/rcv-prod-toolkit/types.git) registered for path 'types'
Cloning into 'E:/repositorios/league-prod-toolkit/docs/wiki'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-caster'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-caster-cockpit'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-ace'...
remote: Repository not found.
fatal: repository 'https://github.com/rcv-prod-toolkit/module-league-champselect-ace.git/' not found
fatal: clone of 'https://github.com/rcv-prod-toolkit/module-league-champselect-ace.git' into submodule path 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-ace' failed
Failed to clone 'modules/module-league-champselect-ace'. Retry scheduled
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-tent'...
remote: Repository not found.
fatal: repository 'https://github.com/rcv-prod-toolkit/module-league-champselect-tent.git/' not found
fatal: clone of 'https://github.com/rcv-prod-toolkit/module-league-champselect-tent.git' into submodule path 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-tent' failed
Failed to clone 'modules/module-league-champselect-tent'. Retry scheduled
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-ui'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-end-of-game'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-in-game'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-prm'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-runes'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-state'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-static'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-teams'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-tournament-tree'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-twitch'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-valorant-pregame'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-valorant-state'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-valorant-static'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-vmix'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/plugin-config'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/plugin-database'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/plugin-prod-clock'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/plugin-theming'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/plugin-webapi'...
Cloning into 'E:/repositorios/league-prod-toolkit/types'...
Cloning into 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-ace'...
remote: Repository not found.
fatal: repository 'https://github.com/rcv-prod-toolkit/module-league-champselect-ace.git/' not found
fatal: clone of 'https://github.com/rcv-prod-toolkit/module-league-champselect-ace.git' into submodule path 'E:/repositorios/league-prod-toolkit/modules/module-league-champselect-ace' failed
Failed to clone 'modules/module-league-champselect-ace' a second time, aborting
```

**Comment by sdomi4** [comment]
This is due to customised variants of the champ select module / custom themes we haven't made public.
You should be able to exclude the submodules in question (`module-league-champselect-ace`, `module-league-champselect-tent`, as well as the themes `theme-league-ace-gaming`, `theme-league-tent`, and `theme-valorant-shooting-stars` from the update either in your [git config or when updating](https://stackoverflow.com/questions/52179463/how-to-exclude-a-specific-git-submodule-from-update).

**Comment by JoanJuan10** [comment]
Hello there. Thank you for the answer.

Following with the next step, I encountered a problem with building the modules.
Here's what pops up whenever I build all modules:
```
Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ npm run build:modules
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> league-prod-toolkit-core@1.3.7 build:modules
> node dist/utils/build-modules.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'E:\repositorios\league-prod-toolkit\dist\utils\build-modules.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
And here is what pops up when I try to build one of them alone:

```
Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ npm run build:modules module-league-static
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> league-prod-toolkit-core@1.3.7 build:modules
> node dist/utils/build-modules.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'E:\repositorios\league-prod-toolkit\dist\utils\build-modules.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

NPM version (I don't know if it's too new. But I don't think its related to my problem):
```
Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ npm -v
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
8.13.2
```

**Comment by sdomi4** [comment]
This error probably appears since the main project isn't built yet.
Should be fixed by executing `npm install` (if you haven't yet) and `npm run build` before `npm run build:modules`.
I have updated the wiki to reflect the full process :)
The npm version should be fine, note we develop and test on node 16.7; newer version probably break things more or less badly.

**Comment by JoanJuan10** [comment]
Thank you for everything. The npm install and build commands work as intended. The only problem now is that the `npm run build:modules` throws some errors since it's missing the modules we skipped before.

Here is a dump of everything that throws the `build:modules` command.

```
Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ npm run build:modules
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> league-prod-toolkit-core@1.3.7 build:modules
> node dist/utils/build-modules.js

installing module-caster
installing module-league-caster-cockpit
installing module-league-champselect-ui
installing module-league-end-of-game
installing module-league-in-game
installing module-league-prm
installing module-league-state
installing module-league-static
installing module-teams
installing module-tournament-tree
installing module-twitch
installing module-valorant-pregame
installing module-valorant-state
installing module-valorant-static
installing module-vmix
installing plugin-config
installing plugin-database
installing plugin-prod-clock
installing plugin-theming
installing plugin-webapi
installing rcv-gfx
Failed to install module: module-league-champselect-ui, Error: Command failed: npm ci
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.20.7
npm WARN Found: @babel/core@7.5.5
npm WARN node_modules/@babel/core
npm WARN   dev @babel/core@"7.5.5" from the root project
npm WARN   106 more (@babel/helper-compilation-targets, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.20.7
npm WARN node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN   @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.18.9" from @babel/preset-env@7.20.2
npm WARN   node_modules/@babel/preset-env
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.20.12
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.13.0" from @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.20.7
npm WARN   node_modules/@babel/preset-env/node_modules/@babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining
npm WARN     @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@"^7.18.9" from @babel/preset-env@7.20.2
npm WARN     node_modules/@babel/preset-env
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @babel/plugin-proposal-class-static-block@7.20.7
npm WARN Found: @babel/core@7.5.5
npm WARN node_modules/@babel/core
npm WARN   dev @babel/core@"7.5.5" from the root project
npm WARN   106 more (@babel/helper-compilation-targets, ...)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer @babel/core@"^7.12.0" from @babel/plugin-proposal-class-static-block@7.20.7
npm WARN node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-class-static-block
npm WARN   @babel/plugin-proposal-class-static-block@"^7.18.6" from @babel/preset-env@7.20.2
npm WARN   node_modules/@babel/preset-env
npm WARN
npm WARN Conflicting peer dependency: @babel/core@7.20.12
npm WARN node_modules/@babel/core
npm WARN   peer @babel/core@"^7.12.0" from @babel/plugin-proposal-class-static-block@7.20.7
npm WARN   node_modules/@babel/preset-env/node_modules/@babel/plugin-proposal-class-static-block
npm WARN     @babel/plugin-proposal-class-static-block@"^7.18.6" from @babel/preset-env@7.20.2
npm WARN     node_modules/@babel/preset-env
npm ERR! code EUSAGE
npm ERR!
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR! Missing: semver@6.3.0 from lock file
npm ERR!
npm ERR! Clean install a project
npm ERR!
npm ERR! Usage:
npm ERR! npm ci
npm ERR!
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR!
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR!
npm ERR! Run "npm help ci" for more info

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joan\AppData\Local\npm-cache\_logs\2023-02-20T14_58_28_498Z-debug-0.log

installed module-league-champselect-ui
====================
start building module-league-champselect-ui

> module-league-champselect-ui@1.6.0 build
> node scripts/build.js


Error: Command failed: npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'dotenv-expand'
Require stack:
- E:\repositorios\league-prod-toolkit\modules\module-league-champselect-ui\config\env.js
- E:\repositorios\league-prod-toolkit\modules\module-league-champselect-ui\scripts\build.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at E:\repositorios\league-prod-toolkit\modules\module-league-champselect-ui\config\env.js:35:5
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (E:\repositorios\league-prod-toolkit\modules\module-league-champselect-ui\config\env.js:33:13)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'E:\\repositorios\\league-prod-toolkit\\modules\\module-league-champselect-ui\\config\\env.js',
    'E:\\repositorios\\league-prod-toolkit\\modules\\module-league-champselect-ui\\scripts\\build.js'
  ]
}

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm run build'
}
```
After that, it starts to build and it seems all existing modules work and build as intended.
```
installed module-league-caster-cockpit
installed plugin-config
installed module-league-end-of-game
installed plugin-prod-clock
installed module-tournament-tree
installed module-caster
installed module-valorant-state
installed module-valorant-pregame
installed module-vmix
installed module-twitch
installed module-league-in-game
installed module-league-state
installed module-teams
installed module-valorant-static
installed plugin-theming
installed plugin-database
installed module-league-static
installed rcv-gfx
====================
start building plugin-config

> plugin-config@3.0.4 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-caster-cockpit

> module-league-caster-cockpit@0.10.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-end-of-game

> module-league-end-of-game@1.4.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building plugin-prod-clock

> plugin-prod-clock@1.1.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-caster

> module-caster@2.0.3 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-state

> module-valorant-state@1.7.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-teams

> module-teams@4.2.1 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-vmix

> module-vmix@0.8.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-twitch

> module-twitch@1.1.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-state

> module-league-state@4.9.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-in-game

> module-league-in-game@3.6.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed module-league-prm
====================
start building module-league-static

> module-league-static@3.9.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-static

> module-valorant-static@1.3.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-pregame

> module-valorant-pregame@1.2.8 build
> npm run compile-sass && tsc


> module-valorant-pregame@1.2.8 compile-sass
> sass frontend/gfx/:frontend/gfx/


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building plugin-database

> plugin-database@2.3.3 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed plugin-webapi
====================
start building plugin-theming

> plugin-theming@1.2.4 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-tournament-tree

> module-tournament-tree@1.2.8 build
> npm run compile-sass && tsc


> module-tournament-tree@1.2.8 compile-sass
> sass frontend/style/:frontend/style/


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building rcv-gfx

> rcv-gfx@1.1.1 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-prm

> module-league-prm@1.0.1 build
> tsc

```
Thank you for the help!

**Comment by sdomi4** [comment]
The error is not related to the other submodules; it's actually failing to build. We'll take a look to see what's happening. The [precompiled version](https://github.com/rcv-prod-toolkit/module-league-champselect-ui/releases) should work in case you don't plan to modify champ select.

**Comment by JoanJuan10** [comment]
I used the precompiled version and it is now building. It seems to be missing a `compile saas` script somewhere though.

 ```
 Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
$ npm run build:modules
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> league-prod-toolkit-core@1.3.7 build:modules
> node dist/utils/build-modules.js

installing module-caster
installing module-league-champselect-ui
installing module-league-caster-cockpit
installing module-league-end-of-game
installing module-league-in-game
installing module-league-prm
installing module-league-static
installing module-league-state
installing module-teams
installing module-tournament-tree
installing module-twitch
installing module-valorant-pregame
installing module-valorant-state
installing module-valorant-static
installing plugin-config
installing module-vmix
installing plugin-database
installing plugin-theming
installing plugin-prod-clock
installing plugin-webapi
installing rcv-gfx
installed module-league-end-of-game
installed module-league-caster-cockpit
installed plugin-database
installed module-valorant-state
installed module-league-in-game
installed module-caster
installed plugin-config
installed module-league-static
installed module-league-state
installed module-twitch
installed module-valorant-pregame
installed module-teams
====================
start building module-league-caster-cockpit

> module-league-caster-cockpit@0.10.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed plugin-prod-clock
====================
start building plugin-database

> plugin-database@2.3.3 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-end-of-game

> module-league-end-of-game@1.4.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-state

> module-valorant-state@1.7.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-in-game

> module-league-in-game@3.6.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-caster

> module-caster@2.0.3 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building plugin-config

> plugin-config@3.0.4 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed module-valorant-static
installed module-vmix
installed module-tournament-tree
installed plugin-theming
====================
start building module-league-static

> module-league-static@3.9.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-league-state

> module-league-state@4.9.5 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed rcv-gfx
====================
start building plugin-prod-clock

> plugin-prod-clock@1.1.5 build
> tsc


Error: Command failed: npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! Missing script: "compile-sass"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Joan\AppData\Local\npm-cache\_logs\2023-02-20T15_20_16_681Z-debug-0.log

    at ChildProcess.exithandler (node:child_process:398:12)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1,
  killed: false,
  signal: null,
  cmd: 'npm run build'
}
====================
start building module-twitch

> module-twitch@1.1.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-teams

> module-teams@4.2.1 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed module-league-prm
====================
start building module-vmix

> module-vmix@0.8.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-static

> module-valorant-static@1.3.2 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building plugin-theming

> plugin-theming@1.2.4 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building rcv-gfx

> rcv-gfx@1.1.1 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-valorant-pregame

> module-valorant-pregame@1.2.8 build
> npm run compile-sass && tsc


> module-valorant-pregame@1.2.8 compile-sass
> sass frontend/gfx/:frontend/gfx/


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

====================
start building module-tournament-tree

> module-tournament-tree@1.2.8 build
> npm run compile-sass && tsc


> module-tournament-tree@1.2.8 compile-sass
> sass frontend/style/:frontend/style/


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed plugin-webapi
====================
start building module-league-prm

> module-league-prm@1.0.1 build
> tsc


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

installed module-league-champselect-ui
====================
start building module-league-champselect-ui

> module-league-champselect-ui@1.6.0 build
> node scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  42.87 kB  build\static\js\2.5838ddc5.chunk.js
  9.58 kB   build\static\js\main.1228372d.chunk.js
  801 B     build\static\js\runtime~main.4bf0a0a6.js
  211 B     build\static\css\main.266321ad.chunk.css

The project was built assuming it is hosted at /pages/op-module-league-champselect-ui/.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.

Find out more about deployment here:

  https://cra.link/deployment


npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.


Joan@DESKTOP-P13L8VS MINGW64 /e/repositorios/league-prod-toolkit (main)
 ```
 
 Edit: Actually it doesn't seem to build. Only that module is.

**Comment by sdomi4** [comment]
The failed build was down to a missing dependency. You can either manually install `dotenv-expand` or pull the newest version to resolve the issue.
