### ISSUE TITLE
Database Error

### ISSUE THREAD

**Issue by ManuelHenao** [RCVolus/league-prod-toolkit#31]
Hi,im getting a database error, i dont know what im doing wrong.

`2021-11-04T05:48:17.372Z [error] lpte-svc    : Request timed out after 5000ms. Request meta={"channelType":"REQUEST","type":"request","namespace":"config","version":1,"sender":{"name":"database","version":"1.0.0","mode":"PLUGIN","path":"C:\\league-prod-toolkit-develop\\modules\\database"},"reply":"request-97s9dsgkvkj2lzo"}
2021-11-04T05:48:17.375Z [warn ] plugin-database: database config could not be loaded
2021-11-04T05:48:17.376Z [warn ] lpte-svc    : Awaiting event timed out. namespace=reply, type=request-97s9dsgkvkj2lzr, timeout=5000
2021-11-04T05:48:17.376Z [error] lpte-svc    : Request timed out after 5000ms. Request meta={"channelType":"REQUEST","type":"request","namespace":"config","version":1,"sender":{"name":"league-in-game","version":"1.0.0","mode":"PLUGIN","path":"C:\\league-prod-toolkit-develop\\modules\\league-in-game"},"reply":"request-97s9dsgkvkj2lzr"}
2021-11-04T05:48:17.376Z [warn ] plugin-league-in-game: config could not be loaded
2021-11-04T05:48:17.855Z [warn ] lpte-svc    : Awaiting event timed out. namespace=reply, type=request-97s9dsgkvkj2md2, timeout=5000
2021-11-04T05:48:17.855Z [error] lpte-svc    : Request timed out after 5000ms. Request meta={"channelType":"REQUEST","type":"request","namespace":"config","version":1,"sender":{"name":"static-league","version":"3.0.0","mode":"PLUGIN","path":"C:\\league-prod-toolkit-develop\\modules\\static-league"},"reply":"request-97s9dsgkvkj2md2"}
2021-11-04T05:48:17.855Z [warn ] plugin-static-league: static-league config could not be loaded
2021-11-04T05:50:42.375Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.376Z [error] plugin-league-end-of-game: Uncaught error in league-end-of-game: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.377Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.377Z [error] plugin-prod-clock: Uncaught error in prod-clock: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.784Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.784Z [error] plugin-provider-webapi: Uncaught error in provider-webapi: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.788Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.789Z [error] plugin-rcv-caster: Uncaught error in rcv-caster: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.790Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.793Z [error] plugin-rcv-teams: Uncaught error in rcv-teams: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.796Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.798Z [error] plugin-state-league: Uncaught error in state-league: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2021-11-04T05:50:42.996Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2021-11-04T05:50:42.996Z [error] plugin-themeing: Uncaught error in themeing: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\league-prod-toolkit-develop\dist\core\eventbus\LPTEService.js:73:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)`

**Comment by ManuelHenao** [comment]
It looks like this at the start

![lol prod toolkit error 1](https://user-images.githubusercontent.com/64715702/140264818-bb919cd5-2b21-44f6-a508-5c7763a90ab6.png)

later (about 1-2 mins) it look like this

![lol prod toolkit error 2](https://user-images.githubusercontent.com/64715702/140264914-8ff8aaad-0c76-44d2-acf3-985377a2ea00.png)

**Comment by ManuelHenao** [comment]
This is the first post, it looks better in image

![lol prod toolkit error 3](https://user-images.githubusercontent.com/64715702/140265209-391e7ef7-e944-4424-afad-dc35d7f016de.png)

**Comment by sdomi4** [comment]
Hi Manuel,
It looks like the toolkit can't find the config, could you double check if you modified and saved the config? (Step 4 here: https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation#install-prod-toolkit)

**Comment by Himyu** [comment]
Did you edit the "config.dist.json" in /modules/config/ into "config.json" like described [here](https://github.com/RCVolus/league-prod-toolkit/wiki/1.-Installation) ?

**Comment by daisukedd** [comment]
I have the same problem

**Comment by ManuelHenao** [comment]
Ok sorry. don read the save as config,json. now working database. but now, if i start prod toolkit and open the league observer tool, prod toolkit closes when i enter to pick and bans.

**Comment by sdomi4** [comment]
> I have the same problem

Could you please check your config as well? see above for the guide

> if i start prod toolkit and open the league observer tool, prod toolkit closes when i enter to pick and bans.

Are you able to connect modules and LCU to the toolkit successfully? Do you receive any kind of error message / popup or does the toolkit window just crash?

**Comment by ManuelHenao** [comment]
It just Close

**Comment by ManuelHenao** [comment]
just happens if i sync chamselect. i tried to sync when im already on champselect and it closes too.

**Comment by ManuelHenao** [comment]
My bad. is working well. just have a conflict with another thing. Thanks

**Comment by Himyu** [comment]
Would you mind telling us what it was conflicting with so we maybe can document it or fix it in the future?

**Comment by ManuelHenao** [comment]
really dont know. just close a lot of things and worked. but nothing about prod toolkit.

**Comment by Himyu** [comment]
Ok well thank you anyway and happy to hear that it works now 👍
