### ISSUE TITLE
PRM TABLE with Challonge

### ISSUE THREAD

**Issue by Marunc1** [RCVolus/league-prod-toolkit#547]
Hello, is there a possibility  to add a bracket from challonge into the prm table? if so, how because i have this error when i try to  do it with this https://loolish.challonge.com/LOLE1/bracket :
``` 
C:\Users\user\Desktop\loolish\lol\modules\module-league-prm\node_modules\string-strip-html\dist\string-strip-html.cjs.js:2020
    throw new TypeError(
          ^

TypeError: string-strip-html/stripHtml(): [THROW_ID_01] Input must be string! Currently it's: undefined, equal to:
undefined
    at stripHtml (C:\Users\user\Desktop\loolish\lol\modules\module-league-prm\node_modules\string-strip-html\dist\string-strip-html.cjs.js:2020:11)
    at C:\Users\user\Desktop\loolish\lol\modules\module-league-prm\dist\plugin.js:26:62
    at Array.map (<anonymous>)
    at Registration.handle (C:\Users\user\Desktop\loolish\lol\modules\module-league-prm\dist\plugin.js:25:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) ```

**Comment by sdomi4** [comment]
The prm-module is made specifically for the prime league brackets. Other pages will not work without modifying the code.
