### ISSUE TITLE
Cannot read 'color'

### ISSUE THREAD

**Issue by Xahrie** [RCVolus/league-prod-toolkit#677]
Im getting the following exception/error inside the console. This is the url of the page:
http://localhost:3003/pages/op-module-league-champselect-ui/champselect.html?apikey=...

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'color')
    at A (index.less:54:1)
    at index.less:54:1
    at s (index.less:54:1)
    at Generator.<anonymous> (index.less:54:1)
    at Generator.next (index.less:54:1)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)

Full Stacktrace:
A	@	index.less:54
(anonymous)	@	index.less:54
s	@	index.less:54
(anonymous)	@	index.less:54
(anonymous)	@	index.less:54
r	@	asyncToGenerator.js:3
u	@	asyncToGenerator.js:25
Promise.then (async)		
r	@	asyncToGenerator.js:13
u	@	asyncToGenerator.js:25
(anonymous)	@	asyncToGenerator.js:32
(anonymous)	@	asyncToGenerator.js:21
_onSocketOpen	@	frontend-lib.ts:26

This results the plugin.js to not work anymore (meaning no buttons are working, etc).

**Comment by Himyu** [comment]
This occurs apparently when there are no teams set
Have to look into a default solution for colors if there are no teams.
