### ISSUE TITLE
Zeri not shown in pick ban phase

### ISSUE THREAD

**Issue by MaximilianRu** [RCVolus/league-prod-toolkit#72]
**Describe the bug**
Zeris Splashart isn't shown when banned in pick ban phase. 
neither is her splashart downlaoded on start

**To Reproduce**
1. pick & ban
2. ban zeri
3. Tadaa Zeri splash not shown

**Expected behavior**
Show Zeri splash

**Comment by sdomi4** [comment]
I am unable to reproduce this, the Zeri splash shows up as expected.
This may be related to the communitydragon not always being up to date on patch days.
Could you verfiy the following:
- Zeri images should be present in \league-prod-toolkit\modules\static-league\frontend\img\champion and the respective subfolders
- If no Zeri images are present, check toolkit output for entries from plugin-static-league, this should provide updates on download status
- If plugin-static-league is not downloading anything and Zeri images are not present, you can try clearing the last-downloaded value from the config file, this forces plugin-static-league to redownload assets:
```
  "static-league": {
    "last-downloaded-version": ""
  },
```

**Comment by MaximilianRu** [comment]
There are no Zeri images present in given folder.
The plugin static-league is unavailable, but listed in the plugins. 
`2022-02-27T11:19:01.069Z [info ] lpte-svc    : Initialized event bus.
2022-02-27T11:19:01.070Z [info ] module-svc  : Initializing module service.
2022-02-27T11:19:01.080Z [info ] module-svc  : Initialized 19 module(s). Now loading plugins.
2022-02-27T11:19:01.081Z [info ] module-svc  : Loaded 19 plugin(s).
2022-02-27T11:19:01.939Z [info ] main        : LoL Toolkit started up successfully.
2022-02-27T11:19:01.942Z [info ] server      : Listening for requests on http://localhost:3003
2022-02-27T11:19:01.943Z [info ] module-svc  : Plugin status changed: plugin=layout-volu-europe, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.943Z [info ] module-svc  : Plugin status changed: plugin=config, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.944Z [info ] module-svc  : Plugin status changed: plugin=example-module, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.944Z [info ] module-svc  : Plugin status changed: plugin=league-end-of-game, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.944Z [info ] module-svc  : Plugin status changed: plugin=prod-clock, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.945Z [info ] module-svc  : Plugin status changed: plugin=provider-webapi, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.945Z [info ] module-svc  : Plugin status changed: plugin=rcv-caster, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.945Z [info ] module-svc  : Plugin status changed: plugin=rcv-gfx, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.946Z [info ] module-svc  : Plugin status changed: plugin=rcv-rune-gfx, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.946Z [info ] module-svc  : Plugin status changed: plugin=rcv-teams, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.947Z [info ] module-svc  : Plugin status changed: plugin=rcv-tournament-tree, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.947Z [info ] module-svc  : Plugin status changed: plugin=state-league, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.947Z [info ] module-svc  : Plugin status changed: plugin=valorant-pregame, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.948Z [info ] module-svc  : Plugin status changed: plugin=valorant-state, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.961Z [info ] module-svc  : Plugin status changed: plugin=themeing, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.962Z [info ] module-svc  : Plugin status changed: plugin=database, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:01.962Z [info ] module-svc  : Plugin status changed: plugin=league-in-game, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:02.048Z [info ] plugin-static-league: start downloading dragontail.tgz
2022-02-27T11:19:02.051Z [info ] plugin-static-league: start downloading additional files
2022-02-27T11:19:02.268Z [info ] module-svc  : Plugin status changed: plugin=valorant-static, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:19:02.667Z [info ] plugin-static-league: finish downloading additional files`

This happend even after cloning the whole repo new

**Comment by sdomi4** [comment]
Based on the output log, the assets have not finished downloading yet :)
These are all the log entries from static-league downloading the assets, once this has finished, restart the toolkit and everything should work as expected:
```
2022-01-23T13:04:27.265Z [info ] plugin-static-league: start downloading dragontail.tgz
2022-01-23T13:04:27.266Z [info ] plugin-static-league: start downloading additional files
2022-01-23T13:04:27.651Z [info ] plugin-static-league: finish downloading additional files
2022-01-23T13:04:42.150Z [info ] plugin-static-league: finish downloading dragontail.tgz
2022-01-23T13:04:42.152Z [info ] plugin-static-league: start unpacking dragontail.tgz
2022-01-23T13:05:04.762Z [info ] plugin-static-league: finish unpacking dragontail.tgz
2022-01-23T13:05:04.844Z [info ] plugin-static-league: moving files to frontend
2022-01-23T13:05:07.628Z [info ] plugin-static-league: delete versioned folder
2022-01-23T13:05:07.629Z [info ] plugin-static-league: start downloading centered images
2022-01-23T13:05:07.637Z [info ] plugin-static-league: finish moving files to frontend
2022-01-23T13:05:07.697Z [info ] plugin-static-league: finish downloading centered images
2022-01-23T13:05:07.990Z [info ] plugin-static-league: finish deleting versioned folder
```

**Comment by MaximilianRu** [comment]
Yes you are right, just let it run for a while and after a series of errors
`Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.148Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.150Z [error] plugin-prod-clock: Uncaught error in prod-clock: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.153Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.158Z [error] plugin-provider-webapi: Uncaught error in provider-webapi: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.161Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.164Z [error] plugin-rcv-caster: Uncaught error in rcv-caster: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.167Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.173Z [error] plugin-rcv-teams: Uncaught error in rcv-teams: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.176Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.177Z [error] plugin-state-league: Uncaught error in state-league: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.179Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.180Z [error] plugin-league-in-game: Uncaught error in league-in-game: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:21:33.182Z [warn ] lpte-svc    : Awaiting event timed out. namespace=lpt, type=ready, timeout=150000
2022-02-27T11:21:33.183Z [error] plugin-themeing: Uncaught error in themeing: request timed out
Error: request timed out
    at Timeout._onTimeout (C:\Users\Maxim\git\league-prod-toolkit\dist\core\eventbus\LPTEService.js:71:24)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
2022-02-27T11:24:38.817Z [info ] plugin-static-league: finish downloading dragontail.tgz
2022-02-27T11:24:38.821Z [info ] plugin-static-league: start unpacking dragontail.tgz
2022-02-27T11:24:59.880Z [info ] plugin-static-league: finish unpacking dragontail.tgz
2022-02-27T11:24:59.970Z [info ] plugin-static-league: moving files to frontend
2022-02-27T11:25:02.882Z [info ] plugin-static-league: delete versioned folder
2022-02-27T11:25:02.883Z [info ] plugin-static-league: start downloading centered images
2022-02-27T11:25:02.893Z [info ] plugin-static-league: finish moving files to frontend
2022-02-27T11:25:02.965Z [info ] plugin-static-league: finish downloading centered images
(node:132) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
    at emitRecursiveRmdirWarning (node:internal/fs/utils:816:13)
    at Object.rmdir (node:internal/fs/promises:542:5)
    at StaticData.removeVersionDir (C:\Users\Maxim\git\league-prod-toolkit\modules\static-league\dist\StaticData.js:142:37)
    at StaticData.copyDDragonFiles (C:\Users\Maxim\git\league-prod-toolkit\modules\static-league\dist\StaticData.js:136:14)
2022-02-27T11:25:03.479Z [info ] plugin-static-league: finish deleting versioned folder
2022-02-27T11:25:03.482Z [info ] module-svc  : Plugin status changed: plugin=static-league, old=UNAVAILABLE, new=RUNNING
2022-02-27T11:25:03.540Z [info ] plugin-config: config for static-league saved!
2022-02-27T11:28:59.351Z [info ] plugin-state-league: Flow: lobby - active`

it downloaded the files like it is supposed to, some other modules closed by the time it finished, but after restarting the the prod tool everything worked fine
